# Generated by Django 5.1.7 on 2025-04-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='date_of_upload',
        ),
        migrations.AddField(
            model_name='audio',
            name='datetime_of_upload',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
